/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.bean.usuario;
import model.dao.auxiliarDAO;
import model.dao.usuarioDAO;

/**
 *
 * @author IFMA
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public TelaLogin() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        lrest = new javax.swing.JLabel();
        luser = new javax.swing.JLabel();
        lsenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        blogar = new javax.swing.JButton();
        bsair = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        jLabel1.setText("imagem");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 153, 51));
        setIconImage(getIconImage());
        setResizable(false);

        lrest.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        lrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagem/logo.png"))); // NOI18N
        lrest.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        luser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagem/tsicons.com-User.png"))); // NOI18N
        luser.setText("Usuario:");

        lsenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagem/tsicons.com-Key.png"))); // NOI18N
        lsenha.setText("Senha:");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        blogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagem/Sem Título-3.png"))); // NOI18N
        blogar.setContentAreaFilled(false);
        blogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogarActionPerformed(evt);
            }
        });
        blogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                blogarKeyPressed(evt);
            }
        });

        bsair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsair.setForeground(new java.awt.Color(255, 255, 255));
        bsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagem/Sem Título-2.png"))); // NOI18N
        bsair.setContentAreaFilled(false);
        bsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsairActionPerformed(evt);
            }
        });
        bsair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bsairKeyPressed(evt);
            }
        });

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagem/Sem Título-1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(luser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lsenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(blogar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bsair, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lrest, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luser)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lsenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bsair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blogar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void blogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogarActionPerformed
        usuarioDAO dao = new usuarioDAO();
        if(dao.checkLogin(txtLogin.getText(), txtSenha.getText())){
            usuarioDAO p = new usuarioDAO();
            usuario pu = p.readForId();
            auxiliarDAO auxiliar = new auxiliarDAO();
            int b = auxiliar.read();
            
            switch(b){
                case 0:
                    MenuADM adm = new MenuADM();
                    adm.setVisible(true);  
                    dispose(); 
                    JOptionPane.showMessageDialog(null, "Bem vindo(a) "+pu.getNomeu()+"!");
                    break;
                case 1:
                    MenuUser user = new MenuUser();
                    user.setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(null, "Bem vindo(a) "+pu.getNomeu()+"!");
                    break;
                case 2:
                    MenuFuncCaix caixa = new MenuFuncCaix();
                    caixa.setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(null, "Bem vindo(a) "+pu.getNomeu()+"!");
                    break;
                case 3:
                    MenuFuncEntre entregador = new MenuFuncEntre();
                    entregador.setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(null, "Bem vindo(a) "+pu.getNomeu()+"!");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Erro 404!");
                    break;
            }
        }else{
            JOptionPane.showMessageDialog(null, "Usuario ou senha invalido!");
        }


//        String user = txtLogin.getText();
//        String senha = new String (txtSenha.getPassword());
//        
//        if("admin".equals(user)&&"admin".equals(senha)){
//            JOptionPane.showMessageDialog(null, "Login efetuado com sucesso!\n Bem vindo ADM!");
//            MenuADM obj = new MenuADM();
//            obj.setVisible(true);
//            dispose();
//        }else{
//            if("user".equals(user)&&"user".equals(senha)){
//                JOptionPane.showMessageDialog(null, "Login efetuado com sucesso!\n Bem vindo usuario!");
//                MenuUser obj = new MenuUser();
//                obj.setVisible(true);
//                dispose();
//            }else{
//                if("funcc".equals(user)&&"funcc".equals(senha)){
//                    JOptionPane.showMessageDialog(null, "Login efetuado com sucesso!\n Bem vindo caixa!");
//                    MenuFuncCaix obj = new MenuFuncCaix();
//                    obj.setVisible(true);
//                    dispose();
//                }else{
//                    if("funce".equals(user)&&"funce".equals(senha)){
//                        JOptionPane.showMessageDialog(null, "Login efetuado com sucesso!\n Bem vindo entregador!");
//                        MenuFuncEntre obj = new MenuFuncEntre();
//                        obj.setVisible(true);
//                        dispose();
//                    }else{
//                        JOptionPane.showMessageDialog(null, "Usuario ou senha invalido!");          
//                    }
//                }
//            }
//        }
        
        
        //if(checkLogin(txtLogin.getText(), new String(txtSenha.getPassword()))){
        //    JOptionPane.showMessageDialog(null, "Login efetuado com sucesso!\n Bem vindo ADM!");
        //    MenuADM obj = new MenuADM();
        //    obj.setVisible(true);
        //    dispose();
        // }else{
        //   JOptionPane.showMessageDialog(null, "Usuario ou senha invalido!");
        //}
    }//GEN-LAST:event_blogarActionPerformed

    private void bsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bsairActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed

    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void blogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_blogarKeyPressed
        if(evt.getKeyChar()==evt.VK_ENTER){
            blogar.doClick();
        }
    }//GEN-LAST:event_blogarKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if(evt.getKeyChar()==evt.VK_ENTER){
            blogar.doClick();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void bsairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bsairKeyPressed
       if(evt.getKeyChar()==evt.VK_ENTER){
            bsair.doClick();
        }
    }//GEN-LAST:event_bsairKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Registro obj = new Registro();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blogar;
    private javax.swing.JButton bsair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lrest;
    private javax.swing.JLabel lsenha;
    private javax.swing.JLabel luser;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

//    public boolean checkLogin(String login, String senha){
//        return login.equals("admin")&& senha.equals("admin");  
   // } 
    
}
